name: train
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python linear.py
          
          echo "# Results" >> report.md
          echo "## Train" >> report.md
          cml-publish train.png --md >> report.md
          echo "## Test" >> report.md
          cml-publish test.png --md >> report.md
          # Write your CML report
          #cat results.txt >> report.md
          cml-send-comment report.md
